// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/auth/external_auth.proto

/*
Package auth is a generated protocol buffer package.

It is generated from these files:
	api/auth/external_auth.proto

It has these top-level messages:
	CheckRequest
	CheckResponse
	AttributeContext
*/
package auth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import envoy_api_v2 "api"
import _ "github.com/golang/protobuf/ptypes/struct"
import google_protobuf3 "github.com/golang/protobuf/ptypes/timestamp"
import google_rpc "google.golang.org/genproto/googleapis/rpc/status"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CheckRequest struct {
	// The request attributes.
	Attributes *AttributeContext `protobuf:"bytes,1,opt,name=attributes" json:"attributes,omitempty"`
}

func (m *CheckRequest) Reset()                    { *m = CheckRequest{} }
func (m *CheckRequest) String() string            { return proto.CompactTextString(m) }
func (*CheckRequest) ProtoMessage()               {}
func (*CheckRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CheckRequest) GetAttributes() *AttributeContext {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type CheckResponse struct {
	// Status `OK` allows the request. Any other status indicates the request should be denied.
	Status *google_rpc.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *CheckResponse) Reset()                    { *m = CheckResponse{} }
func (m *CheckResponse) String() string            { return proto.CompactTextString(m) }
func (*CheckResponse) ProtoMessage()               {}
func (*CheckResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CheckResponse) GetStatus() *google_rpc.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

// An attribute is a piece of metadata that describes an activity on a network.
// For example, the size of an HTTP request, or the status code of an HTTP response.
//
// Each attribute has a type and a name, which is logically defined as a proto message field.
// AttributeContext is a collection of individual attributes.
type AttributeContext struct {
	// The source of a network activity, such as starting a TCP connection.
	// In a multi hop network activity, the source represents the sender of the
	// last hop.
	Source *AttributeContext_Peer `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
	// The destination of a network activity, such as accepting a TCP connection.
	// In a multi hop network activity, the destination represents the receiver of
	// the last hop.
	Destination *AttributeContext_Peer `protobuf:"bytes,2,opt,name=destination" json:"destination,omitempty"`
	// Represents a network request, such as an HTTP request.
	Request *AttributeContext_Request `protobuf:"bytes,4,opt,name=request" json:"request,omitempty"`
	// This is analogous to http_request.headers, however these contents will not be sent to the
	// upstream server. Context_extensions provide an extension mechanism for sending additional
	// information to the auth server without modifying the proto definition. It maps to the internal
	// opaque context in the filter chain.
	ContextExtensions map[string]string `protobuf:"bytes,10,rep,name=context_extensions,json=contextExtensions" json:"context_extensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *AttributeContext) Reset()                    { *m = AttributeContext{} }
func (m *AttributeContext) String() string            { return proto.CompactTextString(m) }
func (*AttributeContext) ProtoMessage()               {}
func (*AttributeContext) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AttributeContext) GetSource() *AttributeContext_Peer {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *AttributeContext) GetDestination() *AttributeContext_Peer {
	if m != nil {
		return m.Destination
	}
	return nil
}

func (m *AttributeContext) GetRequest() *AttributeContext_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *AttributeContext) GetContextExtensions() map[string]string {
	if m != nil {
		return m.ContextExtensions
	}
	return nil
}

// This message defines attributes for a node that handles a network request.
// The node can be either a service or an application that sends, forwards,
// or receives the request. Service peers should fill in the `service`,
// `principal`, and `labels` as appropriate.
type AttributeContext_Peer struct {
	// The address of the peer, this is typically the IP address.
	// It can also be UDS, or others.
	Address *envoy_api_v2.Address `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	// The canonical service name of the peer.
	// It should be set to :ref:`the HTTP x-envoy-downstream-service-cluster
	// <config_http_conn_man_headers_downstream-service-cluster>`
	// If a more trusted source of the service name is available through mTLS/secure naming, it
	// should be used.
	Service string `protobuf:"bytes,2,opt,name=service" json:"service,omitempty"`
	// The labels associated with the peer.
	// These could be pod labels for Kubernetes or tags for VMs.
	// The source of the labels could be an X.509 certificate or other configuration.
	Labels map[string]string `protobuf:"bytes,3,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The authenticated identity of this peer.
	// For example, the identity associated with the workload such as a service account.
	// If an X.509 certificate is used to assert the identity this field should be sourced from
	// `Subject` or `Subject Alternative Names`. The primary identity should be the principal.
	// The principal format is issuer specific.
	// For example
	// SPIFFE format is `spiffe://trust-domain/path`
	// Google account format is `https://accounts.google.com/{userid}`
	Principal string `protobuf:"bytes,4,opt,name=principal" json:"principal,omitempty"`
}

func (m *AttributeContext_Peer) Reset()                    { *m = AttributeContext_Peer{} }
func (m *AttributeContext_Peer) String() string            { return proto.CompactTextString(m) }
func (*AttributeContext_Peer) ProtoMessage()               {}
func (*AttributeContext_Peer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

func (m *AttributeContext_Peer) GetAddress() *envoy_api_v2.Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *AttributeContext_Peer) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *AttributeContext_Peer) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *AttributeContext_Peer) GetPrincipal() string {
	if m != nil {
		return m.Principal
	}
	return ""
}

// Represents a network request, such as an HTTP request.
type AttributeContext_Request struct {
	// The timestamp when the proxy receives the first byte of the request.
	Time *google_protobuf3.Timestamp `protobuf:"bytes,1,opt,name=time" json:"time,omitempty"`
	// HTTP and related requests.
	Http *AttributeContext_HTTPRequest `protobuf:"bytes,2,opt,name=http" json:"http,omitempty"`
}

func (m *AttributeContext_Request) Reset()                    { *m = AttributeContext_Request{} }
func (m *AttributeContext_Request) String() string            { return proto.CompactTextString(m) }
func (*AttributeContext_Request) ProtoMessage()               {}
func (*AttributeContext_Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 1} }

func (m *AttributeContext_Request) GetTime() *google_protobuf3.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *AttributeContext_Request) GetHttp() *AttributeContext_HTTPRequest {
	if m != nil {
		return m.Http
	}
	return nil
}

// This message defines attributes for an HTTP request.
// HTTP, H2, grpc are all considered http requests.
type AttributeContext_HTTPRequest struct {
	// The unique ID for a request, which can be propagated to downstream
	// systems. The ID should have low probability of collision
	// within a single day for a specific service.
	// For http it should be X-Request-ID or equivalent.
	// For tcp is should be a connection id.
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// The HTTP request method, such as `GET`, `POST`.
	Method string `protobuf:"bytes,2,opt,name=method" json:"method,omitempty"`
	// The HTTP request headers. If multiple headers share the same key, they
	// must be merged according to the HTTP spec. All header keys must be
	// lowercased, because HTTP header keys are case-insensitive.
	Headers map[string]string `protobuf:"bytes,3,rep,name=headers" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The HTTP URL path.
	Path string `protobuf:"bytes,4,opt,name=path" json:"path,omitempty"`
	// The HTTP request `Host` or 'Authority` header value.
	Host string `protobuf:"bytes,5,opt,name=host" json:"host,omitempty"`
	// The HTTP URL scheme, such as `http` and `https`.
	Scheme string `protobuf:"bytes,6,opt,name=scheme" json:"scheme,omitempty"`
	// The HTTP URL query in the format of `name1=value`&name2=value2`, as it
	// appears in the first line of the HTTP request. No decoding is performed.
	Query string `protobuf:"bytes,7,opt,name=query" json:"query,omitempty"`
	// The HTTP URL fragment. No URL decoding is performed.
	Fragment string `protobuf:"bytes,8,opt,name=fragment" json:"fragment,omitempty"`
	// The HTTP request size in bytes. If unknown, it must be -1.
	Size int64 `protobuf:"varint,9,opt,name=size" json:"size,omitempty"`
	// The network protocol used with the request, such as
	// "http/1.1", "spdy/3", "h2", "h2c"
	Protocol string `protobuf:"bytes,10,opt,name=protocol" json:"protocol,omitempty"`
}

func (m *AttributeContext_HTTPRequest) Reset()                    { *m = AttributeContext_HTTPRequest{} }
func (m *AttributeContext_HTTPRequest) String() string            { return proto.CompactTextString(m) }
func (*AttributeContext_HTTPRequest) ProtoMessage()               {}
func (*AttributeContext_HTTPRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 2} }

func (m *AttributeContext_HTTPRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AttributeContext_HTTPRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *AttributeContext_HTTPRequest) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *AttributeContext_HTTPRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *AttributeContext_HTTPRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *AttributeContext_HTTPRequest) GetScheme() string {
	if m != nil {
		return m.Scheme
	}
	return ""
}

func (m *AttributeContext_HTTPRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *AttributeContext_HTTPRequest) GetFragment() string {
	if m != nil {
		return m.Fragment
	}
	return ""
}

func (m *AttributeContext_HTTPRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *AttributeContext_HTTPRequest) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func init() {
	proto.RegisterType((*CheckRequest)(nil), "envoy.api.v2.auth.CheckRequest")
	proto.RegisterType((*CheckResponse)(nil), "envoy.api.v2.auth.CheckResponse")
	proto.RegisterType((*AttributeContext)(nil), "envoy.api.v2.auth.AttributeContext")
	proto.RegisterType((*AttributeContext_Peer)(nil), "envoy.api.v2.auth.AttributeContext.Peer")
	proto.RegisterType((*AttributeContext_Request)(nil), "envoy.api.v2.auth.AttributeContext.Request")
	proto.RegisterType((*AttributeContext_HTTPRequest)(nil), "envoy.api.v2.auth.AttributeContext.HTTPRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Authorization service

type AuthorizationClient interface {
	Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
}

type authorizationClient struct {
	cc *grpc.ClientConn
}

func NewAuthorizationClient(cc *grpc.ClientConn) AuthorizationClient {
	return &authorizationClient{cc}
}

func (c *authorizationClient) Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	out := new(CheckResponse)
	err := grpc.Invoke(ctx, "/envoy.api.v2.auth.Authorization/Check", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Authorization service

type AuthorizationServer interface {
	Check(context.Context, *CheckRequest) (*CheckResponse, error)
}

func RegisterAuthorizationServer(s *grpc.Server, srv AuthorizationServer) {
	s.RegisterService(&_Authorization_serviceDesc, srv)
}

func _Authorization_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/envoy.api.v2.auth.Authorization/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServer).Check(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Authorization_serviceDesc = grpc.ServiceDesc{
	ServiceName: "envoy.api.v2.auth.Authorization",
	HandlerType: (*AuthorizationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _Authorization_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/auth/external_auth.proto",
}

func init() { proto.RegisterFile("api/auth/external_auth.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 650 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcf, 0x6f, 0xd3, 0x30,
	0x14, 0x56, 0x7f, 0x2c, 0x5d, 0x5f, 0x37, 0xb4, 0x59, 0x30, 0xa2, 0x68, 0xd2, 0xaa, 0x71, 0xa9,
	0x40, 0x72, 0xa4, 0xc2, 0x01, 0x06, 0x07, 0x46, 0x99, 0x34, 0x4d, 0x3b, 0x4c, 0xd9, 0xc4, 0x01,
	0x0e, 0x93, 0x9b, 0xbc, 0x2d, 0xd6, 0xd2, 0x38, 0xb3, 0x9d, 0x6a, 0xdd, 0x01, 0x89, 0xbf, 0x97,
	0x7f, 0x80, 0x23, 0x8a, 0xed, 0x8c, 0x52, 0x86, 0xd4, 0x9e, 0xe2, 0xf7, 0xe3, 0xfb, 0xf2, 0xf9,
	0xb3, 0x9f, 0x61, 0x97, 0x15, 0x3c, 0x64, 0xa5, 0x4e, 0x43, 0xbc, 0xd3, 0x28, 0x73, 0x96, 0x5d,
	0x56, 0x11, 0x2d, 0xa4, 0xd0, 0x82, 0x6c, 0x63, 0x3e, 0x15, 0x33, 0xca, 0x0a, 0x4e, 0xa7, 0x43,
	0x5a, 0x15, 0x82, 0x6d, 0x03, 0x48, 0x12, 0x89, 0x4a, 0xd9, 0xae, 0x60, 0xf7, 0x5a, 0x88, 0xeb,
	0x0c, 0x43, 0x13, 0x8d, 0xcb, 0xab, 0x50, 0x69, 0x59, 0xc6, 0xda, 0x55, 0xf7, 0x16, 0xab, 0x9a,
	0x4f, 0x50, 0x69, 0x36, 0x29, 0x5c, 0xc3, 0x73, 0xd7, 0x20, 0x8b, 0x38, 0x54, 0x9a, 0xe9, 0xd2,
	0xf1, 0xee, 0x9f, 0xc3, 0xc6, 0x28, 0xc5, 0xf8, 0x26, 0xc2, 0xdb, 0x12, 0x95, 0x26, 0x23, 0x00,
	0xa6, 0xb5, 0xe4, 0xe3, 0x52, 0xa3, 0xf2, 0x1b, 0xfd, 0xc6, 0xa0, 0x37, 0x7c, 0x41, 0xff, 0x91,
	0x48, 0x0f, 0xeb, 0xa6, 0x91, 0xc8, 0x35, 0xde, 0xe9, 0x68, 0x0e, 0xb6, 0xff, 0x1e, 0x36, 0x1d,
	0xa9, 0x2a, 0x44, 0xae, 0x90, 0xbc, 0x04, 0xcf, 0xfe, 0xd5, 0x31, 0x12, 0x6a, 0xf5, 0x50, 0x59,
	0xc4, 0xf4, 0xdc, 0x54, 0x22, 0xd7, 0xb1, 0xff, 0xa3, 0x0b, 0x5b, 0x8b, 0xec, 0xe4, 0x23, 0x78,
	0x4a, 0x94, 0x32, 0x46, 0x47, 0x30, 0x58, 0x42, 0x12, 0x3d, 0x43, 0x94, 0x91, 0xc3, 0x91, 0x13,
	0xe8, 0x25, 0xa8, 0x34, 0xcf, 0x99, 0xe6, 0x22, 0xf7, 0x9b, 0x2b, 0xd2, 0xcc, 0x83, 0xc9, 0x11,
	0x74, 0xa4, 0xf5, 0xcb, 0x6f, 0x1b, 0x9e, 0x57, 0xcb, 0xf0, 0x38, 0x8b, 0xa3, 0x1a, 0x4b, 0x38,
	0x90, 0xd8, 0xd6, 0x2e, 0xab, 0x8b, 0x91, 0x2b, 0x2e, 0x72, 0xe5, 0x43, 0xbf, 0x35, 0xe8, 0x0d,
	0x0f, 0x96, 0x61, 0x74, 0xdf, 0xa3, 0x07, 0xf0, 0x51, 0xae, 0xe5, 0x2c, 0xda, 0x8e, 0x17, 0xf3,
	0xc1, 0xaf, 0x06, 0xb4, 0xab, 0x7d, 0x90, 0x10, 0x3a, 0xee, 0x62, 0x39, 0x27, 0x9f, 0xfd, 0xfd,
	0xa3, 0x43, 0x5b, 0x8c, 0xea, 0x2e, 0xe2, 0x43, 0x47, 0xa1, 0x9c, 0xf2, 0x18, 0x8d, 0x67, 0xdd,
	0xa8, 0x0e, 0xc9, 0x29, 0x78, 0x19, 0x1b, 0x63, 0xa6, 0xfc, 0x96, 0x91, 0xfc, 0x66, 0x59, 0x33,
	0xe9, 0xa9, 0x81, 0x59, 0xb1, 0x8e, 0x83, 0xec, 0x42, 0xb7, 0x90, 0x3c, 0x8f, 0x79, 0xc1, 0x32,
	0xe3, 0x6a, 0x37, 0xfa, 0x93, 0x08, 0xde, 0x41, 0x6f, 0x0e, 0x44, 0xb6, 0xa0, 0x75, 0x83, 0x33,
	0xb3, 0x83, 0x6e, 0x54, 0x2d, 0xc9, 0x53, 0x58, 0x9b, 0xb2, 0xac, 0xac, 0x45, 0xda, 0xe0, 0xa0,
	0xf9, 0xb6, 0x11, 0x7c, 0x87, 0x4e, 0x7d, 0xb9, 0x29, 0xb4, 0xab, 0xc1, 0x70, 0x3b, 0x0f, 0xea,
	0x4b, 0x58, 0x4f, 0x0d, 0xbd, 0xa8, 0xa7, 0x26, 0x32, 0x7d, 0x64, 0x04, 0xed, 0x54, 0xeb, 0xc2,
	0x5d, 0x96, 0x70, 0x99, 0xfd, 0x1d, 0x5f, 0x5c, 0x9c, 0xd5, 0x07, 0x6d, 0xc0, 0xc1, 0xcf, 0x26,
	0xf4, 0xe6, 0xb2, 0xe4, 0x09, 0x34, 0x79, 0xe2, 0xa4, 0x37, 0x79, 0x42, 0x76, 0xc0, 0x9b, 0xa0,
	0x4e, 0x45, 0xe2, 0xa4, 0xbb, 0x88, 0x7c, 0x81, 0x4e, 0x8a, 0x2c, 0x41, 0x59, 0xfb, 0xfb, 0x61,
	0xc5, 0xff, 0xd3, 0x63, 0x0b, 0xb7, 0x3e, 0xd7, 0x64, 0x84, 0x40, 0xbb, 0x60, 0x3a, 0x75, 0x1e,
	0x9b, 0x75, 0x95, 0x4b, 0x85, 0xd2, 0xfe, 0x9a, 0xcd, 0x55, 0xeb, 0x4a, 0x97, 0x8a, 0x53, 0x9c,
	0xa0, 0xef, 0x59, 0x5d, 0x36, 0xaa, 0x9c, 0xbe, 0x2d, 0x51, 0xce, 0xfc, 0x8e, 0x75, 0xda, 0x04,
	0x24, 0x80, 0xf5, 0x2b, 0xc9, 0xae, 0x27, 0x98, 0x6b, 0x7f, 0xdd, 0x14, 0x1e, 0xe2, 0x8a, 0x5d,
	0xf1, 0x7b, 0xf4, 0xbb, 0xfd, 0xc6, 0xa0, 0x15, 0x99, 0x75, 0xd5, 0x6f, 0x6c, 0x8f, 0x45, 0xe6,
	0x83, 0xed, 0xaf, 0xe3, 0xe0, 0x00, 0x36, 0xe6, 0xa5, 0xaf, 0x74, 0xda, 0x9f, 0x61, 0xe7, 0xf1,
	0xa9, 0x58, 0x85, 0x65, 0xf8, 0x0d, 0x36, 0x0f, 0x4b, 0x9d, 0x0a, 0xc9, 0xef, 0xed, 0xc4, 0x9f,
	0xc0, 0x9a, 0x79, 0xd1, 0xc8, 0xde, 0x23, 0x87, 0x30, 0xff, 0x80, 0x06, 0xfd, 0xff, 0x37, 0xd8,
	0xc7, 0xf0, 0x93, 0xf7, 0xb5, 0x5d, 0x65, 0xc7, 0x9e, 0xd9, 0xf0, 0xeb, 0xdf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xab, 0x96, 0x35, 0x7b, 0x1f, 0x06, 0x00, 0x00,
}
